services:
  - type: web
    name: qa-system-streamlit
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run StreamlitApp.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: GOOGLE_API_KEY
        sync: false
